name: mavzed
version: '1.0.0'
summary: mavzed
description: |
  MavZED routine handler application
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

parts:
  mavzed:
    plugin: python
    python-version: python3
    source: .

apps:
  mavzed:
    command: mavzed
    daemon: simple
    restart-condition: on-failure