name: mavzed
version: '1.0.0'
summary: mavzed
description: |
  ZED camera controller
base: core18
grade: stable
confinement: strict

architectures:
  - build-on: [amd64, arm64]
    run-on: [amd64, arm64]

parts:
  mavzed:
    plugin: python
    source: .
    requirements: [ 'requirements.txt' ]

apps:
  mavzed:
    command: mavzed
    daemon: simple
    restart-condition: always